acseo_typesense:
  typesense:
    url: '%env(resolve:TYPESENSE_URL)%'
    key: '%env(resolve:TYPESENSE_KEY)%'
    collection_prefix: 'test_'
  collections:
    books:
      entity: 'App\Entity\Books'
      fields:
        id:
          name: id
          type: primary
        sortable_id:
          entity_attribute: id
          name: sortable_id
          type: int32
        name:
          name: name
          type: string
        author:
          name: author
          type: object
        author.name:
          name: author_name
          type: string
          facet: true
          entity_attribute: author.name
        category:
          name: category
          type: object
        category.name:
          name: category_name
          type: string
          entity_attribute: category.name
        publisher:
          name: publisher
          type: object
        publisher.name:
          name: publisher_name
          type: string
          entity_attribute: publisher.name
        publishedAt:
          name: publishedAt
          type: datetime
          optional: true
      finders:
        books:
          finder_parameters:
            query_by: title
            limit: 10
            prefix: true
            num_typos: 1
            drop_tokens_threshold: 1
      default_sorting_field: sortable_id
      symbols_to_index: ['+']